"use client";

import type React from "react";

import { useState } from "react";
import { SendIcon, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { ChatMessage } from "@/components/chat-message";
import { cn } from "@/lib/utils";
import { ThemeToggle } from "@/components/theme-toggle";
import { ImageUpload } from "@/components/image-upload";
import { GenderSelect } from "@/components/gender-select";

type Message = {
  id: string;
  role: "user" | "assistant";
  content: string;
  image?: string;
};

export function Chat() {
  const [input, setInput] = useState("");
  const [showImageUpload, setShowImageUpload] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      role: "assistant",
      content:
        "Hello! I'm v0, Vercel's AI-powered assistant. How can I help you today?",
    },
  ]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() && !showImageUpload) return;

    // Add user message
    const userMessage: Message = {
      id: Date.now().toString(),
      role: "user",
      content: input,
    };

    // Add assistant response (in a real app, this would come from an API)
    const assistantMessage: Message = {
      id: (Date.now() + 1).toString(),
      role: "assistant",
      content:
        "This is a placeholder response. In a real application, this would be generated by an AI model.",
    };

    setMessages([...messages, userMessage, assistantMessage]);
    setInput("");
    setShowImageUpload(false);
  };

  const handleImageUpload = (file: File) => {
    // In a real app, you would upload this to a server
    // For now, we'll just create a local URL
    const imageUrl = URL.createObjectURL(file);

    // Add user message with image
    const userMessage: Message = {
      id: Date.now().toString(),
      role: "user",
      content: input || "Image uploaded",
      image: imageUrl,
    };

    // Add assistant response
    const assistantMessage: Message = {
      id: (Date.now() + 1).toString(),
      role: "assistant",
      content:
        "I've received your image. In a real application, I would analyze it or respond accordingly.",
    };

    setMessages([...messages, userMessage, assistantMessage]);
    setInput("");
    setShowImageUpload(false);
  };

  return (
    <div className="flex flex-col h-screen max-h-screen">
      <header className="border-b p-4 flex items-center justify-between">
        <h1 className="text-xl font-bold">v0 Interface</h1>
        <ThemeToggle />
      </header>
      <div className="flex-1 overflow-y-auto p-4">
        <div className="max-w-3xl mx-auto">
          {messages.map((message) => (
            <ChatMessage key={message.id} message={message} />
          ))}
        </div>
      </div>
      <div className="border-t bg-background p-4">
        <form onSubmit={handleSubmit} className="max-w-3xl mx-auto space-y-4">
          {showImageUpload && (
            <ImageUpload onImageUpload={handleImageUpload} className="mb-4" />
          )}

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
            <Button
              type="button"
              variant={showImageUpload ? "default" : "outline"}
              onClick={() => setShowImageUpload(!showImageUpload)}
              className="w-full flex items-center justify-center gap-2"
            >
              <Upload className="h-4 w-4" />
              {showImageUpload ? "Hide Upload" : "Upload your image"}
            </Button>
            <div>
              <GenderSelect />
            </div>
          </div>

          <div className="relative">
            <Textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Message v0..."
              className="min-h-[60px] w-full resize-none pr-16 rounded-lg border-muted"
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleSubmit(e);
                }
              }}
            />
            <Button
              type="submit"
              size="icon"
              className={cn(
                "absolute right-2 top-2 h-8 w-8",
                !input.trim() &&
                  !showImageUpload &&
                  "opacity-50 cursor-not-allowed",
              )}
              disabled={!input.trim() && !showImageUpload}
            >
              <SendIcon className="h-4 w-4" />
              <span className="sr-only">Send</span>
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}
